name: Test

on:
  workflow_dispatch: {}
  push: {}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [
          ubuntu-latest,
        ]
        toolchain: [
          stable,
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust Toolchain
        run: |
          rustup toolchain install ${{ matrix.toolchain }} --profile minimal --no-self-update
          rustup default ${{ matrix.toolchain }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Cargo Sweep Stamp
        run: |
          cargo install cargo-sweep
          cargo sweep --stamp

      - name: Copy Example Env
        run: cp env.example .env

      - name: Make Test
        run: make test

      - name: Check No Change
        if: runner.os == 'Linux'
        run: git diff --exit-code

      - name: Cargo Sweep File
        run: cargo sweep --file
